-- Cost CI live experiment: Snowflake setup.  UNVALIDATED (written without account access).
-- Run as a role with CREATE WAREHOUSE / CREATE DATABASE (SYSADMIN by default) in a TRIAL or
-- sandbox account. Everything is created under COSTCI_* names and can be removed with
-- teardown.sql. Expected credit use of this script: a few credits (CTAS of TPC-H SF10).

-- Dedicated, pinned, single-cluster warehouses so measurements are attributable and repeatable.
CREATE WAREHOUSE IF NOT EXISTS COSTCI_CI_WH
  WAREHOUSE_SIZE = 'XSMALL' GENERATION = '1' MAX_CLUSTER_COUNT = 1 MIN_CLUSTER_COUNT = 1
  AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  ENABLE_QUERY_ACCELERATION = FALSE STATEMENT_TIMEOUT_IN_SECONDS = 1800
  COMMENT = 'Cost CI experiment: CI runs';
CREATE WAREHOUSE IF NOT EXISTS COSTCI_PROD_WH
  WAREHOUSE_SIZE = 'SMALL' GENERATION = '1' MAX_CLUSTER_COUNT = 1 MIN_CLUSTER_COUNT = 1
  AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  ENABLE_QUERY_ACCELERATION = FALSE STATEMENT_TIMEOUT_IN_SECONDS = 3600
  COMMENT = 'Cost CI experiment: simulated production runs';

-- Hard spend cap for the whole experiment (set CREDIT_QUOTA to the approved budget).
CREATE RESOURCE MONITOR IF NOT EXISTS COSTCI_CAP WITH CREDIT_QUOTA = 60
  TRIGGERS ON 80 PERCENT DO NOTIFY ON 100 PERCENT DO SUSPEND_IMMEDIATE;
ALTER WAREHOUSE COSTCI_CI_WH SET RESOURCE_MONITOR = COSTCI_CAP;
ALTER WAREHOUSE COSTCI_PROD_WH SET RESOURCE_MONITOR = COSTCI_CAP;

CREATE DATABASE IF NOT EXISTS COSTCI_LAB;
USE DATABASE COSTCI_LAB;
USE WAREHOUSE COSTCI_PROD_WH;
ALTER SESSION SET QUERY_TAG = 'costci:setup';
ALTER SESSION SET USE_CACHED_RESULT = FALSE;

-- SNOWFLAKE_SAMPLE_DATA cannot be cloned (shared database), so copy it with CTAS, physically
-- ordered by date like the local lab so that pruning behaviour is comparable.
CREATE SCHEMA IF NOT EXISTS RAW;           -- production-scale sources (TPC-H SF10)
CREATE OR REPLACE TABLE RAW.LINEITEM AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.LINEITEM ORDER BY L_SHIPDATE, L_ORDERKEY;
CREATE OR REPLACE TABLE RAW.ORDERS   AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.ORDERS   ORDER BY O_ORDERDATE, O_ORDERKEY;
CREATE OR REPLACE TABLE RAW.CUSTOMER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.CUSTOMER;
CREATE OR REPLACE TABLE RAW.PART     AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PART;
CREATE OR REPLACE TABLE RAW.PARTSUPP AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.PARTSUPP;
CREATE OR REPLACE TABLE RAW.SUPPLIER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.SUPPLIER;
CREATE OR REPLACE TABLE RAW.NATION   AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.NATION;
CREATE OR REPLACE TABLE RAW.REGION   AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10.REGION;

-- Key-consistent 10% CI sample (same definition as costci/data.py). RAW_KEY01: same with "< 10".
CREATE SCHEMA IF NOT EXISTS RAW_KEY10;
CREATE OR REPLACE TABLE RAW_KEY10.CUSTOMER AS SELECT * FROM RAW.CUSTOMER WHERE MOD(ABS(HASH(C_CUSTKEY)), 1000) < 100;
CREATE OR REPLACE TABLE RAW_KEY10.ORDERS AS
  SELECT o.* FROM RAW.ORDERS o JOIN RAW_KEY10.CUSTOMER c ON c.C_CUSTKEY = o.O_CUSTKEY ORDER BY O_ORDERDATE, O_ORDERKEY;
CREATE OR REPLACE TABLE RAW_KEY10.LINEITEM AS
  SELECT l.* FROM RAW.LINEITEM l JOIN RAW_KEY10.ORDERS o ON o.O_ORDERKEY = l.L_ORDERKEY ORDER BY L_SHIPDATE, L_ORDERKEY;
CREATE OR REPLACE VIEW RAW_KEY10.PART AS SELECT * FROM RAW.PART;
CREATE OR REPLACE VIEW RAW_KEY10.PARTSUPP AS SELECT * FROM RAW.PARTSUPP;
CREATE OR REPLACE VIEW RAW_KEY10.SUPPLIER AS SELECT * FROM RAW.SUPPLIER;
CREATE OR REPLACE VIEW RAW_KEY10.NATION AS SELECT * FROM RAW.NATION;
CREATE OR REPLACE VIEW RAW_KEY10.REGION AS SELECT * FROM RAW.REGION;

-- Telemetry access for the experiment role (run as ACCOUNTADMIN; least privilege via DB roles):
-- GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE COSTCI_ROLE;       -- metering, attribution
-- GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE COSTCI_ROLE;  -- query + access history
